name: Publish on GitHub Pages

on:
  push:
    branches:
      - gh-pages

inputs:
  version:
    description: "Zola version to use"
    required: true
    default: "v0.19.1"

jobs:
  build:
    runs-on: ubuntu-latest
    using: "composite"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: 'wget -q -O -
          "https://github.com/getzola/zola/releases/download/${{ inputs.version }}/zola-${{ inputs.version }}-x86_64-unknown-linux-gnu.tar.gz"
          | tar xzf - -C /usr/local/bin'
        shell: bash

      - run: zola build
        shell: bash

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
